all:
  hosts:
    staging-web:
      ansible_host: "192.168.203.3"
      proxmox_id: '107'
    staging-print:
      ansible_host: "192.168.203.6"
      proxmox_id: '109'
    prod-web:
      ansible_host: "192.168.203.7"
      proxmox_id: '110'
    prod-print:
      ansible_host: "192.168.203.8"
      proxmox_id: '113'

webserver:
  hosts:
    staging-web:
    prod-web:

printserver:
  hosts:
    staging-print:
      prod-print:

staging:
  hosts:
    staging-web:
    staging-print:

production:
  hosts:
    prod-web:
    prod-print: