---
- name: Load apt updates
  hosts: production
  gather_facts: false
  tasks:
    - name: Apt update
      apt:
        update_cache: yes

- name: Linux staging maintenance
  hosts: staging
  serial: 5
  gather_facts: false
  tasks:
    - name: Create new VM snapshot
      community.general.proxmox_snap:
        api_user: "{{ proxmox_user }}"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        api_host: "{{ proxmox_host }}"
        validate_certs: no
        vmid: "{{ proxmox_id }}"
        snapname: pre-updates
        state: present
        vmstate: yes
      delegate_to: jumpsrv
    - block:
      - name: Apt update
        apt:
          update_cache: yes
      - name: Apt upgrade
        apt:
          upgrade: yes
          autoclean: yes
          autoremove: yes
        register: result
        retries: 3
        delay: 10
        until: result is not failed
      - name: Reboot after Update
        reboot:
          msg: "Automatic Update via ansible"
          connect_timeout: 5
          reboot_timeout: 600
          pre_reboot_delay: 0
          post_reboot_delay: 30
          test_command: whoami
      - name: Check operation
        shell: "{{ check_command }}"
      rescue:
        - set_fact:
            notify_subject: "Operation not succesful!"
        - include_tasks: tasks/send_email.yml
        - name: Restore VM snapshot
          community.general.proxmox_snap:
            api_user: "{{ proxmox_user }}"
            api_token_id: "{{ proxmox_token_id }}"
            api_token_secret: "{{ proxmox_token_secret }}"
            api_host: "{{ proxmox_host }}"
            validate_certs: no
            vmid: "{{ proxmox_id }}"
            snapname: pre-updates
            state: rollback
          delegate_to: jumpsrv
        - name: Restart time sync service
          systemd:
            name: systemd-timesyncd
            state: restarted
        - name: Delete VM snapshot
          community.general.proxmox_snap:
            api_user: "{{ proxmox_user }}"
            api_token_id: "{{ proxmox_token_id }}"
            api_token_secret: "{{ proxmox_token_secret }}"
            api_host: "{{ proxmox_host }}"
            validate_certs: no
            vmid: "{{ proxmox_id }}"
            snapname: pre-updates
            state: absent
          delegate_to: jumpsrv
    - block:
        - name: CheckDNS
          shell: 'nslookup awx.fst91.ein.dev | egrep -q "5.9.222.97"'
        - name: CheckNTP
          shell: 'timedatectl status | egrep -q "System clock synchronized: yes"'
      rescue:
        - set_fact:
            notify_subject: "NTP/DNS not succesful!"
        - include_tasks: tasks/send_email.yml
